name: Mirror Repository to Another GitHub Repo

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Setup Git Config
      run: |
        git config user.name "${{ variable.GIT_COMMITTER_NAME }}"
        git config user.email "${{ variable.GIT_COMMITTER_EMAIL }}"

    - name: Push Mirror
      run: |
        git push --mirror https://x-access-token:${{ secrets.MIRROR_GITHUB_TOKEN }}@github.com/SRH-I4/python_calculator.SCHULZ.git
      env:
        GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
        GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
